FROM akocur/postgresql-1c-17:latest

# Установка необходимых пакетов для 1С
RUN apt-get update && apt-get install -y \
    libpq-dev \
    wget \
    unzip \
    fontconfig \
    ttf-dejavu \
    imagemagick \
    libwebkitgtk-3.0-0 \
    xvfb \
    gdebi-core \
    && rm -rf /var/lib/apt/lists/*

# Создание директории для установки
RUN mkdir -p distributions/

# Установка сервера 1С
RUN cd distributions \
    && dpkg -i 1c-enterprise-8.3*-common_8.3*.deb \
    && dpkg -i 1c-enterprise-8.3*-server_8.3*.deb \
    && dpkg -i 1c-enterprise-8.3*-ws_8.3*.deb \
    && rm -rf /tmp/distributions

WORKDIR /ibservers/main-branch

RUN mkdir -p /dt/main-branch /src/main-branch /cf/main-branch /configs/main-branch

# Переключение на пользователя root для запуска сервисов
USER root

EXPOSE 1540-1541 1560-1591 8080 8282 8314

# Запуск сервисов при старте контейнера
CMD ["/start.sh"]
